<?php

namespace AppBundle\Repository;

/**
 * DocumentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentationRepository extends \Doctrine\ORM\EntityRepository
{
}
