<?php

namespace AppBundle\Repository;

/**
 * ErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorRepository extends \Doctrine\ORM\EntityRepository
{
}
