app:
    resource: "@AppBundle/Controller/"
    type:     annotation
data:
    type: rest
    resource: AppBundle\Controller\RestController
    prefix: /api
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin